version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    container_name: libracont
    restart: always
    environment:
      POSTGRES_DB: "library"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "libra2023"  
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5430:5432
